document.write('<div class="read_set">');
document.write('	<div align="center">背景颜色：');
document.write('		<select id="bcolor" onchange="$(\'body\').css(\'background\', this.value);">');
document.write('			<option value="#d0cfb2" selected="selected">默认设置</option>');
document.write('			<option style="background-color: #e9faff" value="#e9faff">经典淡蓝</option>');
document.write('			<option style="background-color: #f1f1f1" value="#f1f1f1">经典淡灰</option>');
document.write('			<option style="background-color: #eefaee" value="#eefaee">经典绿意</option>');
document.write('			<option style="background-color: #ffffed" value="#ffffed">经典明黄</option>');
document.write('			<option style="background-color: #4394d6" value="#4394d6">深蓝海洋</option>');
document.write('			<option style="background-color: #d0cfb2" value="#d0cfb2">秋意盎然</option>');
document.write('			<option style="background-color: #9fc383" value="#9fc383">绿意淡雅</option>');
document.write('			<option style="background-color: #fcefff" value="#fcefff">红粉世家</option>');
document.write('			<option style="background-color: #fbe5d9" value="#fbe5d9">红谈意浓</option>');
document.write('			<option style="background-color: #c2ceda" value="#c2ceda">海阔天空</option>');
document.write('			<option style="background-color: #616378" value="#616378">心碎过去</option>');
document.write('			<option style="background-color: #ffffff" value="#ffffff">雪白天地</option>');
document.write('			<option style="background-color: #cccccc" value="#cccccc">灰色世界</option>');
document.write('		</select>');
document.write('		字体颜色：');
document.write('		<select id="txtcolor" onchange="$(\'#read_book\').css(\'color\',this.value);">');
document.write('			<option value="#000000" selected="selected">默认设置</option>');
document.write('			<option style="background-color: #FFFFFF" value="#ffffff">白色</option>');
document.write('			<option style="background-color: #ff0000" value="#ff0000">红色</option>');
document.write('			<option style="background-color: #006600" value="#006600">绿色</option>');
document.write('			<option style="background-color: #0000ff" value="#0000ff">蓝色</option>');
document.write('			<option style="background-color: #660000" value="#660000">棕色</option>');
document.write('		</select>');
document.write('		字体大小：');
document.write('		<select id="txtsize" onchange="$(\'#read_book\').css(\'font-size\', this.value);" class="ssot">');
document.write('			<option value="26px">最大</option>');
document.write('			<option value="22px">较大</option>');
document.write('			<option value="14px" selected="selected">中等</option>');
document.write('			<option value="12px">较小</option>');
document.write('			<option value="10px">最小</option>');
document.write('		</select>');
document.write('		鼠标双击滚屏：');
document.write('		<select id="scrollspeed" onchange="setSpeed(this.value);" class="ssot">');
document.write('			<option value="1">1</option>');
document.write('			<option value="2">2</option>');
document.write('			<option value="3">3</option>');
document.write('			<option value="4">4</option>');
document.write('			<option value="5" selected="selected">5</option>');
document.write('			<option value="6">6</option>');
document.write('			<option value="7">7</option>');
document.write('			<option value="8">8</option>');
document.write('			<option value="9">9</option>');
document.write('		</select>');
document.write('		(1最慢，9最快）');
document.write('		<input id="saveset" onclick="saveSet();" type="button" value="保存设置" />');
document.write('	</div>');
document.write('</div>');
