<?php
return array (
  'system' => 
  array (
    'site_name' => '小说网',
    'site_domain' => '',
    'site_index' => '首页',
    'metakeywords' => '',
    'metadescription' => '',
    'site_allow_reg' => 1,
    'site_icp' => '',
    'site_open' => 1,
    'site_close_inform' => '本站关闭中,请后继续访问...',
    'cookie_time' => 0,
    'cookies_domain' => '',
    'max_pagenum' => 20,
  ),
  'book' => 
  array (
    'sort_depth' => 2,
    'chapter_in_db' => 1,
    'chapter_dir' => '/files/chapter/{bid}/',
    'chapter_auto_check' => 1,
    'credit_txt' => 1,
    'credit_umd' => 1,
    'credit_epub' => 1,
    'credit_review' => 1,
    'credit_review_good' => 1,
    'vip_font' => '宋体',
    'vip_font_size' => '16',
    'vip_watermark' => '1',
    'vip_watermark_pic' => 'pic',
    'vip_watermark_place' => 'place',
    'vip_extra_info' => '未完待续',
    'vip_ticket_min_credit' => '300',
    'vip_ticket_per_credit' => '200',
    'ebook_txt_auto' => 0,
    'ebook_txt_type' => 0,
    'ebook_txt_zip' => 1,
    'ebook_umd_auto' => 0,
    'ebook_epub_auto' => 0,
    'url_txt' => '/files/ebook/{bdir}/{bid}/{bid}.txt',
    'url_zip' => '/files/ebook/{bdir}/{bid}/{bid}.zip',
    'url_epub' => '/files/ebook/{bdir}/{bid}/{bid}.epub',
    'url_umd' => '/files/ebook/{bdir}/{bid}/{bid}.umd',
    'url_index' => '/book/{bdir}/{bid}/index',
    'url_menu' => '/book/{bdir}/{bid}/menu',
    'url_read' => '/book/{bdir}/{bid}/{cid}',
    'url_full' => '/book/{bdir}/{bid}/full',
    'url_down' => '/book/{bdir}/{bid}/down',
    'url_top' => '/book/top/{tid}',
    'html_auto' => '0',
    'html_ext' => '.html',
    'chapter_html' => 3,
    'read_volume' => 1,
    'read_full' => 1,
    'perpage_book' => 10,
    'perpage_top' => 100,
    'has_channel' => 1,
    'url_show' => '/book/{sdir}/page_{page}',
    'url_lists' => '/book/{sdir}/index',
    'review_open' => 1,
    'review_auto' => 1,
    'reply_auto' => 1,
    'perpage_review' => 10,
    'perpage_reply' => 10,
    'search_history' => 1,
  ),
  'period_flag' => '1|1|24',
  'HTML_FILE_SUFFIX' => '.html',
  'URL_MODEL' => 3,
  'DEFAULT_THEME' => 'default',
  'DB_TYPE' => 'mysql',
  'DB_CHARSET' => 'utf8',
  'DB_PREFIX' => '{db_prefix}',
  'DB_HOST' => '{db_host}',
  'DB_PORT' => '{db_port}',
  'DB_NAME' => '{db_name}',
  'DB_USER' => '{db_user}',
  'DB_PWD' => '{db_pass}',
);
?>